version: '3.8'

services:
  postgres-atom:
    image: postgres:15
    container_name: postgres-atom
    environment:
      POSTGRES_USER: atom
      POSTGRES_PASSWORD: atom123
      POSTGRES_DB: atom_db
    ports:
      - "5433:5432" # Key Point: Mapea 5433 (host) → 5432 (contenedor), si tienes postgres en local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      -c listen_addresses='*' 
      -c password_encryption=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atom -d atom_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: